version: '3.8'
services:
  bap:
    image: sarfalam/simple-beckn-bap-ride-hailing:1.0.2
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./docker_config/bap/config.yaml:/app/config/bap.yaml
  boilerplate:
    image: sarfalam/bpp-boilerplate-ride-hailing:1.0.4
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "4173:4173"
      - "4000:4000"
      - "4001:4001"
    stdin_open: true 
    tty: true
    volumes:
      - ./docker_config/bpp/sdk.yaml:/app/apps/server/sdk.yaml
      - ./docker_config/bpp/.env:/app/apps/server/.env
      - ./docker_config/agent/.env:/app/apps/agent/.env
      - ./docker_config/admin/.env:/app/apps/admin/.env
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
      # - db:/data/db  
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./docker_config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - boilerplate
      - bap
volumes:
  db: