path: /home/sarfraz/coding/BPP-Boilerplate-SDK/packages/bpp-sdk/src/specifications/1.1.0/api/transaction/build/transaction.yaml
version: 1.1.0
db:
  mongo:
    mongo_uri: mongodb://localhost:27017
    models:
    - name: "Transaction"
      schema:
        txn_id:
          type: string
        order_id:
          type: ObjectId
          ref: Order
          required: true
        status:
          type: string
          default: "initiated"
          enum:
            - "initiated"
            - "in_progress"
            - "completed"
            - "cancelled"
            - "confirmed"
tables:     
  - name: "Mentors"
    for: Provider
    admin_ui: true
    schema:
      name:
        type: string
        as: descriptor.name
      mentor_code:
        type: uuid
        as: descriptor.code
      short_desc:
        type: string
        as: descriptor.short_desc
      mentor_images:
        type: object[]
        as: descriptor.images
        children:
          icon:
            type: upload
            as: url
      subject:
        type: enum
        as: category_id
        enum:
        - code: "MATHS"
          name: "MATHS"
        - code: "ENGLISH"
          name: "ENGLISH"
        - code: "PHYSICS"
          name: "PHYSICS"
        - code: "CHEMISTRY"
          name: "CHEMISTRY"
      packages:
        type: object[]
        as: items
        children:
          id:
            type: uuid
            as: id
          name:
            type: string
            as: descriptor.name
          short_desc:
            type: string
            as: descriptor.short_desc
          price:
            type: object
            as: price
            children:
              value:
                type: string
                as: value

gateway:
    uri: https://gateway.becknprotocol.io/bg
    registry_uri: https://registry.becknprotocol.io/subscribers
app:
    id: sarfraz-bpp-dsep
    unique_id: sarfraz-bpp-dsep-key
    uri: https://sarfraz-bpp.loca.lt
    ttl: PT10M
    city: std:080
    country: IND
    public_key: YcnZ8xyT2M2onkgI+t6W9Ct+6FnsBuiSCa8WqPDLy8k=
    private_key: SiVZmCtmzKdhZ3VUG5ONYKLDdtF1slRPEGZWHMS3DhthydnzHJPYzaieSAj63pb0K37oWewG6JIJrxao8MvLyQ==
